### ISSUE TITLE
Linking to Java static field generates many warnings, and creates dummy ("#") link

### ISSUE THREAD

**Issue by xenomachina** [Kotlin/dokka#131]
When I try to link to a Java static field in my KDoc, Dokka generates many warnings, and creates a dummy link in the generated HTML.

To rule out something wrong with my build, I reproduced this problem in the dokka-gradle-example from  kotlin-examples. I changed the `Greeter` class in HelloWorld.kt to look like this:

```kotlin
/**
 * This class supports greeting people by name to [System.out].
 *
 * @property name The name of the person to be greeted.
 */
class Greeter(val name: String) {

    /**
     * Prints the greeting to the standard output.
     */
    fun greet() {
        System.out.println("Hello $name!")
    }
}
```

Executing `./gradlew dokka` resulted in:

```
:dokka
No documentation for demo$main(kotlin.Array((kotlin.String))) (HelloWorld.kt:18)
Can't find node by signature java.lang.System$out
Can't find node by signature java.lang.System$out
Can't find node by signature java.lang.System$out
Can't find node by signature java.lang.System$out
Can't find node by signature java.lang.System$out
Can't find node by signature java.lang.System$out
Can't find node by signature java.lang.System$out
Can't find node by signature java.lang.System$out

BUILD SUCCESSFUL
```

In the generated HTML the links look like:

```html
<a href="#">System.out</a>
```

At most this should generate one warning, but from the docs I could not see any problem with the link syntax I'm using, so I don't know why it didn't generate a working link. Linking to the class (ie: `System`) or a static method in the class (eg: `System.console()`) both work as expected, so this behavior seems to be peculiar to static fields.

**Comment by czyzby** [comment]
Is there any workaround to temporarily silence such warnings to avoid console flood?

**Comment by raincole** [comment]
Same here, it's crazily spamming my console every time I build the project

**Comment by semoro** [comment]
Fixed in [0.9.14](https://github.com/Kotlin/dokka/releases/tag/0.9.14)

**Comment by czyzby** [comment]
@semoro What was fixed? Because I updated to 0.9.14, and I still get the dummy link in HTML and the console warnings when linking to a Java class. Is there some property that I need to set before generating the documentation? I use Dokka through Gradle.

**Comment by FrancoSabadini** [comment]
I'm still getting these warnings when building using version 0.9.15 in Android Studio 3, I think this ticket should be re-opened.

```
> Task :volleywrapper:dokka
Can't find node by signature com.android.volley.RetryPolicy
Can't find node by signature com.android.volley.toolbox.RequestFuture$get()
Can't find node by signature com.android.volley.RetryPolicy
Can't find node by signature com.hipsheep.volleywrapper.Configuration$retryPolicy
Can't find node by signature com.android.volley.RetryPolicy
...
```

**Comment by semoro** [comment]
No, it not warnings about Java static fields, which was fixed @FrancoSabadini

**Comment by reisi007** [comment]
Can't find node by signature java.lang.System$currentTimeMillis() in 0.9.15,
 this is also fixed in 0.9.16-eap-2 (+better error message - thanks for that!)
[I found this issue via Google, so just in case ;) ]
