### ISSUE TITLE
Enum entry table is not full width

### ISSUE THREAD

**Issue by MarcinAman** [Kotlin/dokka#1572]
![image](https://user-images.githubusercontent.com/15652452/96251362-9f86bb80-0fb0-11eb-990a-fac215b20186.png)

**Comment by IgnatBeresnev** [comment]
Relevant as of 1.8.10

**Comment by MGaetan89** [comment]
I think this is fixed in the latest version of Dokka:
<img width="841" height="427" alt="Image" src="https://github.com/user-attachments/assets/c5b11613-31b6-411b-8a25-4ce408c8af2d" />

**Comment by whyoleg** [comment]
It works fine in the HTML format, but the issue is still there for javadoc format:

<img width="1133" height="528" alt="Image" src="https://github.com/user-attachments/assets/c2b4fed1-65ce-416e-a164-6baaba13a2c4" />

**Comment by MGaetan89** [comment]
My bad, I missed that it's the Javadoc version. I though it was an old design 😅
