### ISSUE TITLE
New lines in Java source Javadoc code blocks are not preserved in dokka HTML output

### ISSUE THREAD

**Issue by eskatos** [Kotlin/dokka#158]
Given a Java type with some Javadoc, e.g.:

```java
/**
 * Something that matters.
 *
 * <pre>
 * with( some ) {
 *     multi = lines
 *     sample()
 * }
 * </pre>
 */
public interface Something {}
```

All lines in the `<pre/>` element are rendered as a single line in dokka HTML output.

As an example:
- [Java source for Copy](https://github.com/gradle/gradle/blob/d60b527ff902fd0710f64972ad25f7ed02c289bc/subprojects/core/src/main/java/org/gradle/api/tasks/Copy.java#L29-L69)
- [Javadoc output for Copy](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/Copy.html)
- [dokka output for Copy](https://gradle.github.io/kotlin-dsl-docs/api/org.gradle.api.tasks/-copy/index.html)

**Comment by semoro** [comment]
Fixed in [0.9.14](https://github.com/Kotlin/dokka/releases/tag/0.9.14)

**Comment by eskatos** [comment]
Hi @semoro,
Thanks for looking into this.

I just tried `0.9.14` but it seems to me that it is not fixed, see the `dokka` output for the Gradle `Copy` task mentioned above: https://gradle.github.io/kotlin-dsl-docs/api/org.gradle.api.tasks/-copy/index.html

**Comment by eskatos** [comment]
It may be because in this case there's an attribute on the `<pre>` tag: https://github.com/gradle/gradle/blob/d60b527ff902fd0710f64972ad25f7ed02c289bc/subprojects/core/src/main/java/org/gradle/api/tasks/Copy.java#L34

If that's actually the cause, shall I open another issue for this?

**Comment by semoro** [comment]
Just reopen this
