### ISSUE TITLE
Can't find node by signature

### ISSUE THREAD

**Issue by asarkar** [Kotlin/dokka#1617]
**Describe the bug**
Useless warnings flooding build logs.

**Expected behaviour**
The opposite of above.

**Screenshots**
https://github.com/asarkar/jsemver/runs/1388963414?check_suite_focus=true

<img width="1278" alt="dokka" src="https://user-images.githubusercontent.com/1302775/98903895-528dec00-246d-11eb-8b1a-6492b25d6924.png">

**To Reproduce**
N/A.

**Dokka configuration**
```kotlin
tasks.withType<org.jetbrains.dokka.gradle.DokkaTask> {
    outputFormat = "html"
    outputDirectory = "$buildDir/javadoc"
}
```

**Installation**
- Operating system: All
- Build tool: Gradle v6.5.1
- Dokka version: 0.10.1

**Comment by DanySK** [comment]
I believe this has been fixed in Dokka 1.4.x. Just upgrade your Dokka.

**Comment by asarkar** [comment]
Fixed in Dokka 1.4, closing.

**Comment by asarkar** [comment]
Reopened since only the message changed, but the problem remains.
```
Conflicting documentation for org.antlr.v4.runtime/Lexer/setTokenFactory/#org.antlr.v4.runtime.TokenFactory<?>/PointingToDeclaration/[org.antlr.v4.runtime/Recognizer/setTokenFactory/#org.antlr.v4.runtime.TokenFactory<?>/PointingToDeclaration/, org.antlr.v4.runtime/TokenSource/setTokenFactory/#org.antlr.v4.runtime.TokenFactory<?>/PointingToDeclaration/]
Conflicting documentation for org.antlr.v4.runtime/Lexer/getTokenFactory/#/PointingToDeclaration/[org.antlr.v4.runtime/Recognizer/getTokenFactory/#/PointingToDeclaration/, org.antlr.v4.runtime/TokenSource/getTokenFactory/#/PointingToDeclaration/]
Conflicting documentation for org.antlr.v4.runtime/Lexer/getInputStream/#/PointingToDeclaration/[org.antlr.v4.runtime/Recognizer/getInputStream/#/PointingToDeclaration/, org.antlr.v4.runtime/TokenSource/getInputStream/#/PointingToDeclaration/]

```

**Comment by DanySK** [comment]
I don't think it's the same problem, you are hijacking this thread.
And by the way the message you quoted seems to me very legitimate.

**Comment by asarkar** [comment]
It can’t be legit if it’s not even my code. I’m not hijacking this thread, you’re missing the point that Dokka should stop spamming build logs. People shouldn’t have to open a ticket for every single line just because you choose to downplay the problem.

**Comment by DanySK** [comment]
Spamming is a thing, warning is another. Anyway, no need to argue with you.

**Comment by asarkar** [comment]
That’s correct, you’ve got nothing to base your argument on. Saves both of us time.

**Comment by MarcinAman** [comment]
Eh, please stop arguing, it is not a place for that. 

Dokka tries to be explicit about the items it finds in source code. In this situation it did not find a documentation for a base method but found multiple documentations for super method, so this was logged. This is not spamming, if you don't like the logs you can ignore them or if you really don't want to see them, redirect to dev/null.

Closing since it is an intended behaviour

**Comment by asarkar** [comment]
@MarcinAman The problem is that the “warnings” are on a third-party class that’s in a jar, and not in my source set. It’s not about liking or disliking the messages. It makes no sense to notify the user, me, and requiring me to suppress it.
